# gpg --batch --full-generate-key support/gpg-release-key.conf
%echo Generating CIDVerse Release Key
Key-Type: EdDSA
Key-Curve: Ed25519
Key-Usage: cert
Name-Real: CIDVerse Release Sign Key
Name-Email: release.cidverse.sign@philippheuer.de
Expire-Date: 1y
%ask-passphrase
%no-protection

# Now define the Signing Subkey
Subkey-Type: EdDSA
Subkey-Curve: Ed25519
Subkey-Usage: sign
Subkey-Expire-Date: 1y

# Do the generation
%commit
%echo Done
