package githubreleasepublish

import (
	"context"
	"fmt"
	"os"

	"github.com/cidverse/cid/pkg/builtin/builtinaction/common"
	"github.com/cidverse/cid/pkg/core/actionsdk"
	"github.com/google/go-github/v84/github"
	"golang.org/x/oauth2"

	cidsdk "github.com/cidverse/cid-sdk-go"
	"github.com/cidverse/cidverseutils/version"
)

const URI = "builtin://actions/github-release-publish"

type Action struct {
	Sdk actionsdk.SDKClient
}

type Config struct {
	GitHubToken string `json:"github_token"  env:"GITHUB_TOKEN"`
}

func (a Action) Metadata() cidsdk.ActionMetadata {
	return cidsdk.ActionMetadata{
		Name:        "github-release-publish",
		Description: "Publishes a new release on GitHub, including the release notes and artifacts.",
		Category:    "publish",
		Scope:       cidsdk.ActionScopeProject,
		Rules: []cidsdk.ActionRule{
			{
				Type:       "cel",
				Expression: `hasPrefix(ENV["NCI_REPOSITORY_REMOTE"], "https://github.com/")`,
			},
		},
		Access: cidsdk.ActionAccess{
			Environment: []cidsdk.ActionAccessEnv{
				{
					Name:        "GITHUB_TOKEN",
					Description: "The GitHub token to use for creating the release.",
					Required:    true,
				},
			},
			Executables: []cidsdk.ActionAccessExecutable{},
		},
		Input: cidsdk.ActionInput{
			Artifacts: []cidsdk.ActionArtifactType{
				{
					Type: "changelog",
				},
				{
					Type: "binary",
				},
			},
		},
	}
}

func (a Action) GetConfig(d *actionsdk.ProjectExecutionContextV1Response) (Config, error) {
	cfg := Config{}

	if err := common.ParseAndValidateConfig(d.Config.Config, d.Env, &cfg); err != nil {
		return cfg, err
	}

	return cfg, nil
}

func (a Action) Execute() (err error) {
	// query action data
	d, err := a.Sdk.ProjectExecutionContextV1()
	if err != nil {
		return err
	}

	// parse config
	cfg, err := a.GetConfig(d)
	if err != nil {
		return err
	}

	// properties
	ctx := context.Background()
	owner := d.Env["NCI_PROJECT_NAMESPACE_SLUG"]
	repo := d.Env["NCI_PROJECT_NAME_SLUG"]

	// changelog
	changelog, changelogErr := a.Sdk.ArtifactDownloadByteArrayV1(actionsdk.ArtifactDownloadByteArrayRequest{
		ID: "root|changelog|github.changelog",
	})

	// release artifacts
	artifacts, err := a.Sdk.ArtifactListV1(actionsdk.ArtifactListRequest{Query: `(artifact_type == "binary" || artifact_type == "signature")`})
	if err != nil {
		return err
	}
	_ = a.Sdk.LogV1(actionsdk.LogV1Request{Level: "info", Message: "searching for artifacts to include in the release", Context: map[string]interface{}{"artifact_count": len(artifacts)}})
	for _, artifact := range artifacts {
		targetFile := cidsdk.JoinPath(d.Config.TempDir, artifact.Name)
		_, dlErr := a.Sdk.ArtifactDownloadV1(actionsdk.ArtifactDownloadRequest{
			ID:         artifact.ArtifactID,
			TargetFile: targetFile,
		})
		if dlErr != nil {
			_ = a.Sdk.LogV1(actionsdk.LogV1Request{Level: "warn", Message: "failed to retrieve release artifact", Context: map[string]interface{}{"artifact": fmt.Sprintf("%s-%s", artifact.Module, artifact.Name)}})
			continue
		}
	}

	// options
	releaseOptions := &github.RepositoryRelease{
		TagName:    github.Ptr(d.Env["NCI_COMMIT_REF_NAME"]),
		Name:       github.Ptr(d.Env["NCI_COMMIT_REF_NAME"]),
		Prerelease: github.Ptr(!version.IsStable(d.Env["NCI_COMMIT_REF_NAME"])),
		Draft:      github.Ptr(true),
		Assets:     make([]*github.ReleaseAsset, 0),
	}
	if changelogErr == nil && changelog != nil && len(changelog.Bytes) > 0 { // use changelog generated by pipeline, default to GitHub auto generated release notes if not available
		releaseOptions.Body = github.Ptr(string(changelog.Bytes))
	} else {
		releaseOptions.GenerateReleaseNotes = github.Ptr(true)
	}

	// create client
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: cfg.GitHubToken})
	tc := oauth2.NewClient(ctx, ts)
	client := github.NewClient(tc)

	// create release
	_ = a.Sdk.LogV1(actionsdk.LogV1Request{Level: "info", Message: "creating github draft release"})
	release, _, err := client.Repositories.CreateRelease(ctx, owner, repo, releaseOptions)
	if err != nil {
		return fmt.Errorf("failed to create github release: %w", err)
	}

	// release artifacts
	for _, artifact := range artifacts {
		err = func() error {
			targetFile := cidsdk.JoinPath(d.Config.TempDir, artifact.Name)

			file, err := os.Open(targetFile)
			if err != nil {
				return fmt.Errorf("failed to open %s: %w", targetFile, err)
			}
			defer file.Close()

			_ = a.Sdk.LogV1(actionsdk.LogV1Request{Level: "info", Message: "uploading artifact", Context: map[string]interface{}{"name": artifact.Name}})

			_, _, err = client.Repositories.UploadReleaseAsset(ctx, owner, repo, release.GetID(), &github.UploadOptions{Name: artifact.Name}, file)
			return err
		}()

		if err != nil {
			return fmt.Errorf("failed to upload asset %s: %w", artifact.Name, err)
		}
	}

	// publish
	_ = a.Sdk.LogV1(actionsdk.LogV1Request{Level: "info", Message: "publishing release"})
	_, _, err = client.Repositories.EditRelease(ctx, owner, repo, release.GetID(), &github.RepositoryRelease{
		Draft: github.Ptr(false),
	})
	if err != nil {
		return fmt.Errorf("failed to publish release: %w", err)
	}

	return nil
}
