package appgithub

import (
	"github.com/cidverse/cid/pkg/common/dependency"
	"github.com/cidverse/cid/pkg/constants"
	"github.com/cidverse/cid/pkg/core/catalog"
)

var mergeRequestFooter = "This PR has been generated by the [CID GitHub App](https://github.com/apps/cid-workflow)."

var githubNetworkAllowList = []catalog.ActionAccessNetwork{
	// GitHub Platform
	{Host: "github.com:443"},
	{Host: "api.github.com:443"},
	{Host: "codeload.github.com:443"},
	{Host: "uploads.github.com:443"},
	{Host: "objects.githubusercontent.com:443"},
	{Host: "raw.githubusercontent.com:443"},
	{Host: "release-assets.githubusercontent.com:443"},
	// GitHub Container Registry
	{Host: "ghcr.io:443"},
	{Host: "pkg-containers.githubusercontent.com:443"},
}

var githubWorkflowDependencyList = []dependency.Dependency{
	// tools
	{
		Id:      "cidverse/cid",
		Type:    "github",
		Version: constants.Version,
		Hash:    constants.BinaryHash,
	},
	// github-actions
	{
		Id:      "actions/checkout",
		Type:    "github-action",
		Version: "v6.0.2",
		Hash:    "de0fac2e4500dabe0009e67214ff5f5447ce83dd",
	},
	{
		Id:      "actions/download-artifact",
		Type:    "github-action",
		Version: "v8.0.1",
		Hash:    "3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c",
	},
	{
		Id:      "actions/upload-artifact",
		Type:    "github-action",
		Version: "v7.0.0",
		Hash:    "bbbca2ddaa5d8feaa63e36b76fdaad77386f024f",
	},
	{
		Id:      "step-security/harden-runner",
		Type:    "github-action",
		Version: "v2.16.0",
		Hash:    "fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594",
	},
	// see https://github.com/actions/runner-images
	{
		Id:      "ubuntu",
		Type:    "github-action-runner-image",
		Version: "24.04",
	},
	{
		Id:      "windows",
		Type:    "github-action-runner-image",
		Version: "2025",
	},
}

var githubWorkflowDependencies = func() map[string]dependency.Dependency {
	m := make(map[string]dependency.Dependency, len(githubWorkflowDependencyList))
	for _, dep := range githubWorkflowDependencyList {
		//slog.Debug("GitHub Dependency ID: " + dep.AsPackageUrlNoVersion())
		m[dep.AsPackageUrlNoVersion()] = dep
	}
	return m
}()
