package appgithub

import (
	"github.com/cidverse/cid/pkg/app/appconfig"
	"github.com/cidverse/cid/pkg/core/catalog"
)

var mergeRequestFooter = "This PR has been generated by the [CID GitHub App](https://github.com/apps/cid-workflow)."

var githubNetworkAllowList = []catalog.ActionAccessNetwork{
	// GitHub Platform
	{Host: "github.com:443"},
	{Host: "api.github.com:443"},
	{Host: "codeload.github.com:443"},
	{Host: "uploads.github.com:443"},
	{Host: "objects.githubusercontent.com:443"},
	{Host: "raw.githubusercontent.com:443"},
	{Host: "release-assets.githubusercontent.com:443"},
	// GitHub Container Registry
	{Host: "ghcr.io:443"},
	{Host: "pkg-containers.githubusercontent.com:443"},
}

var githubWorkflowDependencies = map[string]appconfig.WorkflowDependency{
	"cid": {
		Id:      "cid",
		Type:    "binary",
		Version: "0.5.0",
	},
	"actions/checkout": {
		Id:      "actions/checkout",
		Type:    "github-action",
		Version: "v5.0.0",
		Hash:    "08c6903cd8c0fde910a37f88322edcfb5dd907a8",
	},
	"actions/download-artifact": {
		Id:      "actions/download-artifact",
		Type:    "github-action",
		Version: "v5.0.0",
		Hash:    "634f93cb2916e3fdff6788551b99b062d0335ce0",
	},
	"actions/upload-artifact": {
		Id:      "actions/upload-artifact",
		Type:    "github-action",
		Version: "v4.6.2",
		Hash:    "ea165f8d65b6e75b540449e92b4886f43607fa02",
	},
	"step-security/harden-runner": {
		Id:      "step-security/harden-runner",
		Type:    "github-action",
		Version: "v2.13.1",
		Hash:    "f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a",
	},
	"cidverse/ghact-cid-setup": {
		Id:      "cidverse/ghact-cid-setup",
		Type:    "github-action",
		Version: "v0.2.0",
		Hash:    "c6dac0517d28bd8871c195fee9a6bd5a5854d5cb",
	},
}
