// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actionsdk

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSDKClient creates a new instance of MockSDKClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSDKClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSDKClient {
	mock := &MockSDKClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSDKClient is an autogenerated mock type for the SDKClient type
type MockSDKClient struct {
	mock.Mock
}

type MockSDKClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSDKClient) EXPECT() *MockSDKClient_Expecter {
	return &MockSDKClient_Expecter{mock: &_m.Mock}
}

// ArtifactByIdV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ArtifactByIdV1(id string) (*Artifact, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ArtifactByIdV1")
	}

	var r0 *Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Artifact, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Artifact); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ArtifactByIdV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArtifactByIdV1'
type MockSDKClient_ArtifactByIdV1_Call struct {
	*mock.Call
}

// ArtifactByIdV1 is a helper method to define mock.On call
//   - id string
func (_e *MockSDKClient_Expecter) ArtifactByIdV1(id interface{}) *MockSDKClient_ArtifactByIdV1_Call {
	return &MockSDKClient_ArtifactByIdV1_Call{Call: _e.mock.On("ArtifactByIdV1", id)}
}

func (_c *MockSDKClient_ArtifactByIdV1_Call) Run(run func(id string)) *MockSDKClient_ArtifactByIdV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_ArtifactByIdV1_Call) Return(artifact *Artifact, err error) *MockSDKClient_ArtifactByIdV1_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockSDKClient_ArtifactByIdV1_Call) RunAndReturn(run func(id string) (*Artifact, error)) *MockSDKClient_ArtifactByIdV1_Call {
	_c.Call.Return(run)
	return _c
}

// ArtifactDownloadByteArrayV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ArtifactDownloadByteArrayV1(request ArtifactDownloadByteArrayRequest) (*ArtifactDownloadByteArrayResult, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ArtifactDownloadByteArrayV1")
	}

	var r0 *ArtifactDownloadByteArrayResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ArtifactDownloadByteArrayRequest) (*ArtifactDownloadByteArrayResult, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(ArtifactDownloadByteArrayRequest) *ArtifactDownloadByteArrayResult); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ArtifactDownloadByteArrayResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ArtifactDownloadByteArrayRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ArtifactDownloadByteArrayV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArtifactDownloadByteArrayV1'
type MockSDKClient_ArtifactDownloadByteArrayV1_Call struct {
	*mock.Call
}

// ArtifactDownloadByteArrayV1 is a helper method to define mock.On call
//   - request ArtifactDownloadByteArrayRequest
func (_e *MockSDKClient_Expecter) ArtifactDownloadByteArrayV1(request interface{}) *MockSDKClient_ArtifactDownloadByteArrayV1_Call {
	return &MockSDKClient_ArtifactDownloadByteArrayV1_Call{Call: _e.mock.On("ArtifactDownloadByteArrayV1", request)}
}

func (_c *MockSDKClient_ArtifactDownloadByteArrayV1_Call) Run(run func(request ArtifactDownloadByteArrayRequest)) *MockSDKClient_ArtifactDownloadByteArrayV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ArtifactDownloadByteArrayRequest
		if args[0] != nil {
			arg0 = args[0].(ArtifactDownloadByteArrayRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_ArtifactDownloadByteArrayV1_Call) Return(artifactDownloadByteArrayResult *ArtifactDownloadByteArrayResult, err error) *MockSDKClient_ArtifactDownloadByteArrayV1_Call {
	_c.Call.Return(artifactDownloadByteArrayResult, err)
	return _c
}

func (_c *MockSDKClient_ArtifactDownloadByteArrayV1_Call) RunAndReturn(run func(request ArtifactDownloadByteArrayRequest) (*ArtifactDownloadByteArrayResult, error)) *MockSDKClient_ArtifactDownloadByteArrayV1_Call {
	_c.Call.Return(run)
	return _c
}

// ArtifactDownloadV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ArtifactDownloadV1(request ArtifactDownloadRequest) (*ArtifactDownloadResult, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ArtifactDownloadV1")
	}

	var r0 *ArtifactDownloadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ArtifactDownloadRequest) (*ArtifactDownloadResult, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(ArtifactDownloadRequest) *ArtifactDownloadResult); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ArtifactDownloadResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ArtifactDownloadRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ArtifactDownloadV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArtifactDownloadV1'
type MockSDKClient_ArtifactDownloadV1_Call struct {
	*mock.Call
}

// ArtifactDownloadV1 is a helper method to define mock.On call
//   - request ArtifactDownloadRequest
func (_e *MockSDKClient_Expecter) ArtifactDownloadV1(request interface{}) *MockSDKClient_ArtifactDownloadV1_Call {
	return &MockSDKClient_ArtifactDownloadV1_Call{Call: _e.mock.On("ArtifactDownloadV1", request)}
}

func (_c *MockSDKClient_ArtifactDownloadV1_Call) Run(run func(request ArtifactDownloadRequest)) *MockSDKClient_ArtifactDownloadV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ArtifactDownloadRequest
		if args[0] != nil {
			arg0 = args[0].(ArtifactDownloadRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_ArtifactDownloadV1_Call) Return(artifactDownloadResult *ArtifactDownloadResult, err error) *MockSDKClient_ArtifactDownloadV1_Call {
	_c.Call.Return(artifactDownloadResult, err)
	return _c
}

func (_c *MockSDKClient_ArtifactDownloadV1_Call) RunAndReturn(run func(request ArtifactDownloadRequest) (*ArtifactDownloadResult, error)) *MockSDKClient_ArtifactDownloadV1_Call {
	_c.Call.Return(run)
	return _c
}

// ArtifactListV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ArtifactListV1(request ArtifactListRequest) ([]*Artifact, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ArtifactListV1")
	}

	var r0 []*Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ArtifactListRequest) ([]*Artifact, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(ArtifactListRequest) []*Artifact); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ArtifactListRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ArtifactListV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArtifactListV1'
type MockSDKClient_ArtifactListV1_Call struct {
	*mock.Call
}

// ArtifactListV1 is a helper method to define mock.On call
//   - request ArtifactListRequest
func (_e *MockSDKClient_Expecter) ArtifactListV1(request interface{}) *MockSDKClient_ArtifactListV1_Call {
	return &MockSDKClient_ArtifactListV1_Call{Call: _e.mock.On("ArtifactListV1", request)}
}

func (_c *MockSDKClient_ArtifactListV1_Call) Run(run func(request ArtifactListRequest)) *MockSDKClient_ArtifactListV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ArtifactListRequest
		if args[0] != nil {
			arg0 = args[0].(ArtifactListRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_ArtifactListV1_Call) Return(artifacts []*Artifact, err error) *MockSDKClient_ArtifactListV1_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockSDKClient_ArtifactListV1_Call) RunAndReturn(run func(request ArtifactListRequest) ([]*Artifact, error)) *MockSDKClient_ArtifactListV1_Call {
	_c.Call.Return(run)
	return _c
}

// ArtifactUploadV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ArtifactUploadV1(request ArtifactUploadRequest) (string, string, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ArtifactUploadV1")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(ArtifactUploadRequest) (string, string, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(ArtifactUploadRequest) string); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ArtifactUploadRequest) string); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(ArtifactUploadRequest) error); ok {
		r2 = returnFunc(request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSDKClient_ArtifactUploadV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArtifactUploadV1'
type MockSDKClient_ArtifactUploadV1_Call struct {
	*mock.Call
}

// ArtifactUploadV1 is a helper method to define mock.On call
//   - request ArtifactUploadRequest
func (_e *MockSDKClient_Expecter) ArtifactUploadV1(request interface{}) *MockSDKClient_ArtifactUploadV1_Call {
	return &MockSDKClient_ArtifactUploadV1_Call{Call: _e.mock.On("ArtifactUploadV1", request)}
}

func (_c *MockSDKClient_ArtifactUploadV1_Call) Run(run func(request ArtifactUploadRequest)) *MockSDKClient_ArtifactUploadV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ArtifactUploadRequest
		if args[0] != nil {
			arg0 = args[0].(ArtifactUploadRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_ArtifactUploadV1_Call) Return(filePath string, fileHash string, err error) *MockSDKClient_ArtifactUploadV1_Call {
	_c.Call.Return(filePath, fileHash, err)
	return _c
}

func (_c *MockSDKClient_ArtifactUploadV1_Call) RunAndReturn(run func(request ArtifactUploadRequest) (string, string, error)) *MockSDKClient_ArtifactUploadV1_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ConfigV1() (*ConfigV1Response, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigV1")
	}

	var r0 *ConfigV1Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ConfigV1Response, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ConfigV1Response); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConfigV1Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ConfigV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigV1'
type MockSDKClient_ConfigV1_Call struct {
	*mock.Call
}

// ConfigV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) ConfigV1() *MockSDKClient_ConfigV1_Call {
	return &MockSDKClient_ConfigV1_Call{Call: _e.mock.On("ConfigV1")}
}

func (_c *MockSDKClient_ConfigV1_Call) Run(run func()) *MockSDKClient_ConfigV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_ConfigV1_Call) Return(configV1Response *ConfigV1Response, err error) *MockSDKClient_ConfigV1_Call {
	_c.Call.Return(configV1Response, err)
	return _c
}

func (_c *MockSDKClient_ConfigV1_Call) RunAndReturn(run func() (*ConfigV1Response, error)) *MockSDKClient_ConfigV1_Call {
	_c.Call.Return(run)
	return _c
}

// DeploymentV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) DeploymentV1() (*DeploymentV1Response, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeploymentV1")
	}

	var r0 *DeploymentV1Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*DeploymentV1Response, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *DeploymentV1Response); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeploymentV1Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_DeploymentV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeploymentV1'
type MockSDKClient_DeploymentV1_Call struct {
	*mock.Call
}

// DeploymentV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) DeploymentV1() *MockSDKClient_DeploymentV1_Call {
	return &MockSDKClient_DeploymentV1_Call{Call: _e.mock.On("DeploymentV1")}
}

func (_c *MockSDKClient_DeploymentV1_Call) Run(run func()) *MockSDKClient_DeploymentV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_DeploymentV1_Call) Return(deploymentV1Response *DeploymentV1Response, err error) *MockSDKClient_DeploymentV1_Call {
	_c.Call.Return(deploymentV1Response, err)
	return _c
}

func (_c *MockSDKClient_DeploymentV1_Call) RunAndReturn(run func() (*DeploymentV1Response, error)) *MockSDKClient_DeploymentV1_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) EnvironmentV1() (*EnvironmentV1Response, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentV1")
	}

	var r0 *EnvironmentV1Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*EnvironmentV1Response, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *EnvironmentV1Response); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EnvironmentV1Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_EnvironmentV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentV1'
type MockSDKClient_EnvironmentV1_Call struct {
	*mock.Call
}

// EnvironmentV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) EnvironmentV1() *MockSDKClient_EnvironmentV1_Call {
	return &MockSDKClient_EnvironmentV1_Call{Call: _e.mock.On("EnvironmentV1")}
}

func (_c *MockSDKClient_EnvironmentV1_Call) Run(run func()) *MockSDKClient_EnvironmentV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_EnvironmentV1_Call) Return(environmentV1Response *EnvironmentV1Response, err error) *MockSDKClient_EnvironmentV1_Call {
	_c.Call.Return(environmentV1Response, err)
	return _c
}

func (_c *MockSDKClient_EnvironmentV1_Call) RunAndReturn(run func() (*EnvironmentV1Response, error)) *MockSDKClient_EnvironmentV1_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteCommandV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ExecuteCommandV1(req ExecuteCommandV1Request) (*ExecuteCommandV1Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCommandV1")
	}

	var r0 *ExecuteCommandV1Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ExecuteCommandV1Request) (*ExecuteCommandV1Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(ExecuteCommandV1Request) *ExecuteCommandV1Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ExecuteCommandV1Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ExecuteCommandV1Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ExecuteCommandV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCommandV1'
type MockSDKClient_ExecuteCommandV1_Call struct {
	*mock.Call
}

// ExecuteCommandV1 is a helper method to define mock.On call
//   - req ExecuteCommandV1Request
func (_e *MockSDKClient_Expecter) ExecuteCommandV1(req interface{}) *MockSDKClient_ExecuteCommandV1_Call {
	return &MockSDKClient_ExecuteCommandV1_Call{Call: _e.mock.On("ExecuteCommandV1", req)}
}

func (_c *MockSDKClient_ExecuteCommandV1_Call) Run(run func(req ExecuteCommandV1Request)) *MockSDKClient_ExecuteCommandV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ExecuteCommandV1Request
		if args[0] != nil {
			arg0 = args[0].(ExecuteCommandV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_ExecuteCommandV1_Call) Return(executeCommandV1Response *ExecuteCommandV1Response, err error) *MockSDKClient_ExecuteCommandV1_Call {
	_c.Call.Return(executeCommandV1Response, err)
	return _c
}

func (_c *MockSDKClient_ExecuteCommandV1_Call) RunAndReturn(run func(req ExecuteCommandV1Request) (*ExecuteCommandV1Response, error)) *MockSDKClient_ExecuteCommandV1_Call {
	_c.Call.Return(run)
	return _c
}

// FileCopyV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) FileCopyV1(old string, new string) error {
	ret := _mock.Called(old, new)

	if len(ret) == 0 {
		panic("no return value specified for FileCopyV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(old, new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_FileCopyV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileCopyV1'
type MockSDKClient_FileCopyV1_Call struct {
	*mock.Call
}

// FileCopyV1 is a helper method to define mock.On call
//   - old string
//   - new string
func (_e *MockSDKClient_Expecter) FileCopyV1(old interface{}, new interface{}) *MockSDKClient_FileCopyV1_Call {
	return &MockSDKClient_FileCopyV1_Call{Call: _e.mock.On("FileCopyV1", old, new)}
}

func (_c *MockSDKClient_FileCopyV1_Call) Run(run func(old string, new string)) *MockSDKClient_FileCopyV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSDKClient_FileCopyV1_Call) Return(err error) *MockSDKClient_FileCopyV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_FileCopyV1_Call) RunAndReturn(run func(old string, new string) error) *MockSDKClient_FileCopyV1_Call {
	_c.Call.Return(run)
	return _c
}

// FileExistsV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) FileExistsV1(file string) bool {
	ret := _mock.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for FileExistsV1")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(file)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSDKClient_FileExistsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExistsV1'
type MockSDKClient_FileExistsV1_Call struct {
	*mock.Call
}

// FileExistsV1 is a helper method to define mock.On call
//   - file string
func (_e *MockSDKClient_Expecter) FileExistsV1(file interface{}) *MockSDKClient_FileExistsV1_Call {
	return &MockSDKClient_FileExistsV1_Call{Call: _e.mock.On("FileExistsV1", file)}
}

func (_c *MockSDKClient_FileExistsV1_Call) Run(run func(file string)) *MockSDKClient_FileExistsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_FileExistsV1_Call) Return(b bool) *MockSDKClient_FileExistsV1_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSDKClient_FileExistsV1_Call) RunAndReturn(run func(file string) bool) *MockSDKClient_FileExistsV1_Call {
	_c.Call.Return(run)
	return _c
}

// FileListV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) FileListV1(req FileV1Request) ([]File, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for FileListV1")
	}

	var r0 []File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(FileV1Request) ([]File, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(FileV1Request) []File); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(FileV1Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_FileListV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileListV1'
type MockSDKClient_FileListV1_Call struct {
	*mock.Call
}

// FileListV1 is a helper method to define mock.On call
//   - req FileV1Request
func (_e *MockSDKClient_Expecter) FileListV1(req interface{}) *MockSDKClient_FileListV1_Call {
	return &MockSDKClient_FileListV1_Call{Call: _e.mock.On("FileListV1", req)}
}

func (_c *MockSDKClient_FileListV1_Call) Run(run func(req FileV1Request)) *MockSDKClient_FileListV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 FileV1Request
		if args[0] != nil {
			arg0 = args[0].(FileV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_FileListV1_Call) Return(files []File, err error) *MockSDKClient_FileListV1_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockSDKClient_FileListV1_Call) RunAndReturn(run func(req FileV1Request) ([]File, error)) *MockSDKClient_FileListV1_Call {
	_c.Call.Return(run)
	return _c
}

// FileReadV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) FileReadV1(file string) (string, error) {
	ret := _mock.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for FileReadV1")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(file)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(file)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_FileReadV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileReadV1'
type MockSDKClient_FileReadV1_Call struct {
	*mock.Call
}

// FileReadV1 is a helper method to define mock.On call
//   - file string
func (_e *MockSDKClient_Expecter) FileReadV1(file interface{}) *MockSDKClient_FileReadV1_Call {
	return &MockSDKClient_FileReadV1_Call{Call: _e.mock.On("FileReadV1", file)}
}

func (_c *MockSDKClient_FileReadV1_Call) Run(run func(file string)) *MockSDKClient_FileReadV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_FileReadV1_Call) Return(s string, err error) *MockSDKClient_FileReadV1_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSDKClient_FileReadV1_Call) RunAndReturn(run func(file string) (string, error)) *MockSDKClient_FileReadV1_Call {
	_c.Call.Return(run)
	return _c
}

// FileRemoveV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) FileRemoveV1(file string) error {
	ret := _mock.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for FileRemoveV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_FileRemoveV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileRemoveV1'
type MockSDKClient_FileRemoveV1_Call struct {
	*mock.Call
}

// FileRemoveV1 is a helper method to define mock.On call
//   - file string
func (_e *MockSDKClient_Expecter) FileRemoveV1(file interface{}) *MockSDKClient_FileRemoveV1_Call {
	return &MockSDKClient_FileRemoveV1_Call{Call: _e.mock.On("FileRemoveV1", file)}
}

func (_c *MockSDKClient_FileRemoveV1_Call) Run(run func(file string)) *MockSDKClient_FileRemoveV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_FileRemoveV1_Call) Return(err error) *MockSDKClient_FileRemoveV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_FileRemoveV1_Call) RunAndReturn(run func(file string) error) *MockSDKClient_FileRemoveV1_Call {
	_c.Call.Return(run)
	return _c
}

// FileRenameV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) FileRenameV1(old string, new string) error {
	ret := _mock.Called(old, new)

	if len(ret) == 0 {
		panic("no return value specified for FileRenameV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(old, new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_FileRenameV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileRenameV1'
type MockSDKClient_FileRenameV1_Call struct {
	*mock.Call
}

// FileRenameV1 is a helper method to define mock.On call
//   - old string
//   - new string
func (_e *MockSDKClient_Expecter) FileRenameV1(old interface{}, new interface{}) *MockSDKClient_FileRenameV1_Call {
	return &MockSDKClient_FileRenameV1_Call{Call: _e.mock.On("FileRenameV1", old, new)}
}

func (_c *MockSDKClient_FileRenameV1_Call) Run(run func(old string, new string)) *MockSDKClient_FileRenameV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSDKClient_FileRenameV1_Call) Return(err error) *MockSDKClient_FileRenameV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_FileRenameV1_Call) RunAndReturn(run func(old string, new string) error) *MockSDKClient_FileRenameV1_Call {
	_c.Call.Return(run)
	return _c
}

// FileWriteV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) FileWriteV1(file string, content []byte) error {
	ret := _mock.Called(file, content)

	if len(ret) == 0 {
		panic("no return value specified for FileWriteV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(file, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_FileWriteV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileWriteV1'
type MockSDKClient_FileWriteV1_Call struct {
	*mock.Call
}

// FileWriteV1 is a helper method to define mock.On call
//   - file string
//   - content []byte
func (_e *MockSDKClient_Expecter) FileWriteV1(file interface{}, content interface{}) *MockSDKClient_FileWriteV1_Call {
	return &MockSDKClient_FileWriteV1_Call{Call: _e.mock.On("FileWriteV1", file, content)}
}

func (_c *MockSDKClient_FileWriteV1_Call) Run(run func(file string, content []byte)) *MockSDKClient_FileWriteV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSDKClient_FileWriteV1_Call) Return(err error) *MockSDKClient_FileWriteV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_FileWriteV1_Call) RunAndReturn(run func(file string, content []byte) error) *MockSDKClient_FileWriteV1_Call {
	_c.Call.Return(run)
	return _c
}

// HealthV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) HealthV1() (HealthV1Response, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthV1")
	}

	var r0 HealthV1Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (HealthV1Response, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() HealthV1Response); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(HealthV1Response)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_HealthV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthV1'
type MockSDKClient_HealthV1_Call struct {
	*mock.Call
}

// HealthV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) HealthV1() *MockSDKClient_HealthV1_Call {
	return &MockSDKClient_HealthV1_Call{Call: _e.mock.On("HealthV1")}
}

func (_c *MockSDKClient_HealthV1_Call) Run(run func()) *MockSDKClient_HealthV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_HealthV1_Call) Return(healthV1Response HealthV1Response, err error) *MockSDKClient_HealthV1_Call {
	_c.Call.Return(healthV1Response, err)
	return _c
}

func (_c *MockSDKClient_HealthV1_Call) RunAndReturn(run func() (HealthV1Response, error)) *MockSDKClient_HealthV1_Call {
	_c.Call.Return(run)
	return _c
}

// LogV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) LogV1(req LogV1Request) error {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for LogV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(LogV1Request) error); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_LogV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogV1'
type MockSDKClient_LogV1_Call struct {
	*mock.Call
}

// LogV1 is a helper method to define mock.On call
//   - req LogV1Request
func (_e *MockSDKClient_Expecter) LogV1(req interface{}) *MockSDKClient_LogV1_Call {
	return &MockSDKClient_LogV1_Call{Call: _e.mock.On("LogV1", req)}
}

func (_c *MockSDKClient_LogV1_Call) Run(run func(req LogV1Request)) *MockSDKClient_LogV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 LogV1Request
		if args[0] != nil {
			arg0 = args[0].(LogV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_LogV1_Call) Return(err error) *MockSDKClient_LogV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_LogV1_Call) RunAndReturn(run func(req LogV1Request) error) *MockSDKClient_LogV1_Call {
	_c.Call.Return(run)
	return _c
}

// ModuleCurrentV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ModuleCurrentV1() (*ProjectModule, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModuleCurrentV1")
	}

	var r0 *ProjectModule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ProjectModule, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ProjectModule); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProjectModule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ModuleCurrentV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModuleCurrentV1'
type MockSDKClient_ModuleCurrentV1_Call struct {
	*mock.Call
}

// ModuleCurrentV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) ModuleCurrentV1() *MockSDKClient_ModuleCurrentV1_Call {
	return &MockSDKClient_ModuleCurrentV1_Call{Call: _e.mock.On("ModuleCurrentV1")}
}

func (_c *MockSDKClient_ModuleCurrentV1_Call) Run(run func()) *MockSDKClient_ModuleCurrentV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_ModuleCurrentV1_Call) Return(projectModule *ProjectModule, err error) *MockSDKClient_ModuleCurrentV1_Call {
	_c.Call.Return(projectModule, err)
	return _c
}

func (_c *MockSDKClient_ModuleCurrentV1_Call) RunAndReturn(run func() (*ProjectModule, error)) *MockSDKClient_ModuleCurrentV1_Call {
	_c.Call.Return(run)
	return _c
}

// ModuleExecutionContextV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ModuleExecutionContextV1() (*ModuleExecutionContextV1Response, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModuleExecutionContextV1")
	}

	var r0 *ModuleExecutionContextV1Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ModuleExecutionContextV1Response, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ModuleExecutionContextV1Response); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ModuleExecutionContextV1Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ModuleExecutionContextV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModuleExecutionContextV1'
type MockSDKClient_ModuleExecutionContextV1_Call struct {
	*mock.Call
}

// ModuleExecutionContextV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) ModuleExecutionContextV1() *MockSDKClient_ModuleExecutionContextV1_Call {
	return &MockSDKClient_ModuleExecutionContextV1_Call{Call: _e.mock.On("ModuleExecutionContextV1")}
}

func (_c *MockSDKClient_ModuleExecutionContextV1_Call) Run(run func()) *MockSDKClient_ModuleExecutionContextV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_ModuleExecutionContextV1_Call) Return(moduleExecutionContextV1Response *ModuleExecutionContextV1Response, err error) *MockSDKClient_ModuleExecutionContextV1_Call {
	_c.Call.Return(moduleExecutionContextV1Response, err)
	return _c
}

func (_c *MockSDKClient_ModuleExecutionContextV1_Call) RunAndReturn(run func() (*ModuleExecutionContextV1Response, error)) *MockSDKClient_ModuleExecutionContextV1_Call {
	_c.Call.Return(run)
	return _c
}

// ModuleListV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ModuleListV1() ([]*ProjectModule, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModuleListV1")
	}

	var r0 []*ProjectModule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*ProjectModule, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*ProjectModule); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ProjectModule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ModuleListV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModuleListV1'
type MockSDKClient_ModuleListV1_Call struct {
	*mock.Call
}

// ModuleListV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) ModuleListV1() *MockSDKClient_ModuleListV1_Call {
	return &MockSDKClient_ModuleListV1_Call{Call: _e.mock.On("ModuleListV1")}
}

func (_c *MockSDKClient_ModuleListV1_Call) Run(run func()) *MockSDKClient_ModuleListV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_ModuleListV1_Call) Return(projectModules []*ProjectModule, err error) *MockSDKClient_ModuleListV1_Call {
	_c.Call.Return(projectModules, err)
	return _c
}

func (_c *MockSDKClient_ModuleListV1_Call) RunAndReturn(run func() ([]*ProjectModule, error)) *MockSDKClient_ModuleListV1_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectExecutionContextV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ProjectExecutionContextV1() (*ProjectExecutionContextV1Response, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectExecutionContextV1")
	}

	var r0 *ProjectExecutionContextV1Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ProjectExecutionContextV1Response, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ProjectExecutionContextV1Response); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProjectExecutionContextV1Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_ProjectExecutionContextV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectExecutionContextV1'
type MockSDKClient_ProjectExecutionContextV1_Call struct {
	*mock.Call
}

// ProjectExecutionContextV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) ProjectExecutionContextV1() *MockSDKClient_ProjectExecutionContextV1_Call {
	return &MockSDKClient_ProjectExecutionContextV1_Call{Call: _e.mock.On("ProjectExecutionContextV1")}
}

func (_c *MockSDKClient_ProjectExecutionContextV1_Call) Run(run func()) *MockSDKClient_ProjectExecutionContextV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_ProjectExecutionContextV1_Call) Return(projectExecutionContextV1Response *ProjectExecutionContextV1Response, err error) *MockSDKClient_ProjectExecutionContextV1_Call {
	_c.Call.Return(projectExecutionContextV1Response, err)
	return _c
}

func (_c *MockSDKClient_ProjectExecutionContextV1_Call) RunAndReturn(run func() (*ProjectExecutionContextV1Response, error)) *MockSDKClient_ProjectExecutionContextV1_Call {
	_c.Call.Return(run)
	return _c
}

// TARCreateV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) TARCreateV1(inputDirectory string, outputFile string) error {
	ret := _mock.Called(inputDirectory, outputFile)

	if len(ret) == 0 {
		panic("no return value specified for TARCreateV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(inputDirectory, outputFile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_TARCreateV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TARCreateV1'
type MockSDKClient_TARCreateV1_Call struct {
	*mock.Call
}

// TARCreateV1 is a helper method to define mock.On call
//   - inputDirectory string
//   - outputFile string
func (_e *MockSDKClient_Expecter) TARCreateV1(inputDirectory interface{}, outputFile interface{}) *MockSDKClient_TARCreateV1_Call {
	return &MockSDKClient_TARCreateV1_Call{Call: _e.mock.On("TARCreateV1", inputDirectory, outputFile)}
}

func (_c *MockSDKClient_TARCreateV1_Call) Run(run func(inputDirectory string, outputFile string)) *MockSDKClient_TARCreateV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSDKClient_TARCreateV1_Call) Return(err error) *MockSDKClient_TARCreateV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_TARCreateV1_Call) RunAndReturn(run func(inputDirectory string, outputFile string) error) *MockSDKClient_TARCreateV1_Call {
	_c.Call.Return(run)
	return _c
}

// TARExtractV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) TARExtractV1(archiveFile string, outputDirectory string) error {
	ret := _mock.Called(archiveFile, outputDirectory)

	if len(ret) == 0 {
		panic("no return value specified for TARExtractV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(archiveFile, outputDirectory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_TARExtractV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TARExtractV1'
type MockSDKClient_TARExtractV1_Call struct {
	*mock.Call
}

// TARExtractV1 is a helper method to define mock.On call
//   - archiveFile string
//   - outputDirectory string
func (_e *MockSDKClient_Expecter) TARExtractV1(archiveFile interface{}, outputDirectory interface{}) *MockSDKClient_TARExtractV1_Call {
	return &MockSDKClient_TARExtractV1_Call{Call: _e.mock.On("TARExtractV1", archiveFile, outputDirectory)}
}

func (_c *MockSDKClient_TARExtractV1_Call) Run(run func(archiveFile string, outputDirectory string)) *MockSDKClient_TARExtractV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSDKClient_TARExtractV1_Call) Return(err error) *MockSDKClient_TARExtractV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_TARExtractV1_Call) RunAndReturn(run func(archiveFile string, outputDirectory string) error) *MockSDKClient_TARExtractV1_Call {
	_c.Call.Return(run)
	return _c
}

// UUIDV4 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) UUIDV4() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UUIDV4")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSDKClient_UUIDV4_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UUIDV4'
type MockSDKClient_UUIDV4_Call struct {
	*mock.Call
}

// UUIDV4 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) UUIDV4() *MockSDKClient_UUIDV4_Call {
	return &MockSDKClient_UUIDV4_Call{Call: _e.mock.On("UUIDV4")}
}

func (_c *MockSDKClient_UUIDV4_Call) Run(run func()) *MockSDKClient_UUIDV4_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_UUIDV4_Call) Return(s string) *MockSDKClient_UUIDV4_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSDKClient_UUIDV4_Call) RunAndReturn(run func() string) *MockSDKClient_UUIDV4_Call {
	_c.Call.Return(run)
	return _c
}

// VCSCommitByHashV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) VCSCommitByHashV1(request VCSCommitByHashRequest) (*VCSCommit, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for VCSCommitByHashV1")
	}

	var r0 *VCSCommit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(VCSCommitByHashRequest) (*VCSCommit, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(VCSCommitByHashRequest) *VCSCommit); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VCSCommit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(VCSCommitByHashRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_VCSCommitByHashV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VCSCommitByHashV1'
type MockSDKClient_VCSCommitByHashV1_Call struct {
	*mock.Call
}

// VCSCommitByHashV1 is a helper method to define mock.On call
//   - request VCSCommitByHashRequest
func (_e *MockSDKClient_Expecter) VCSCommitByHashV1(request interface{}) *MockSDKClient_VCSCommitByHashV1_Call {
	return &MockSDKClient_VCSCommitByHashV1_Call{Call: _e.mock.On("VCSCommitByHashV1", request)}
}

func (_c *MockSDKClient_VCSCommitByHashV1_Call) Run(run func(request VCSCommitByHashRequest)) *MockSDKClient_VCSCommitByHashV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 VCSCommitByHashRequest
		if args[0] != nil {
			arg0 = args[0].(VCSCommitByHashRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_VCSCommitByHashV1_Call) Return(vCSCommit *VCSCommit, err error) *MockSDKClient_VCSCommitByHashV1_Call {
	_c.Call.Return(vCSCommit, err)
	return _c
}

func (_c *MockSDKClient_VCSCommitByHashV1_Call) RunAndReturn(run func(request VCSCommitByHashRequest) (*VCSCommit, error)) *MockSDKClient_VCSCommitByHashV1_Call {
	_c.Call.Return(run)
	return _c
}

// VCSCommitsV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) VCSCommitsV1(request VCSCommitsRequest) ([]*VCSCommit, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for VCSCommitsV1")
	}

	var r0 []*VCSCommit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(VCSCommitsRequest) ([]*VCSCommit, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(VCSCommitsRequest) []*VCSCommit); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*VCSCommit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(VCSCommitsRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_VCSCommitsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VCSCommitsV1'
type MockSDKClient_VCSCommitsV1_Call struct {
	*mock.Call
}

// VCSCommitsV1 is a helper method to define mock.On call
//   - request VCSCommitsRequest
func (_e *MockSDKClient_Expecter) VCSCommitsV1(request interface{}) *MockSDKClient_VCSCommitsV1_Call {
	return &MockSDKClient_VCSCommitsV1_Call{Call: _e.mock.On("VCSCommitsV1", request)}
}

func (_c *MockSDKClient_VCSCommitsV1_Call) Run(run func(request VCSCommitsRequest)) *MockSDKClient_VCSCommitsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 VCSCommitsRequest
		if args[0] != nil {
			arg0 = args[0].(VCSCommitsRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_VCSCommitsV1_Call) Return(vCSCommits []*VCSCommit, err error) *MockSDKClient_VCSCommitsV1_Call {
	_c.Call.Return(vCSCommits, err)
	return _c
}

func (_c *MockSDKClient_VCSCommitsV1_Call) RunAndReturn(run func(request VCSCommitsRequest) ([]*VCSCommit, error)) *MockSDKClient_VCSCommitsV1_Call {
	_c.Call.Return(run)
	return _c
}

// VCSDiffV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) VCSDiffV1(request VCSDiffRequest) ([]VCSDiff, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for VCSDiffV1")
	}

	var r0 []VCSDiff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(VCSDiffRequest) ([]VCSDiff, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(VCSDiffRequest) []VCSDiff); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]VCSDiff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(VCSDiffRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_VCSDiffV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VCSDiffV1'
type MockSDKClient_VCSDiffV1_Call struct {
	*mock.Call
}

// VCSDiffV1 is a helper method to define mock.On call
//   - request VCSDiffRequest
func (_e *MockSDKClient_Expecter) VCSDiffV1(request interface{}) *MockSDKClient_VCSDiffV1_Call {
	return &MockSDKClient_VCSDiffV1_Call{Call: _e.mock.On("VCSDiffV1", request)}
}

func (_c *MockSDKClient_VCSDiffV1_Call) Run(run func(request VCSDiffRequest)) *MockSDKClient_VCSDiffV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 VCSDiffRequest
		if args[0] != nil {
			arg0 = args[0].(VCSDiffRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_VCSDiffV1_Call) Return(vCSDiffs []VCSDiff, err error) *MockSDKClient_VCSDiffV1_Call {
	_c.Call.Return(vCSDiffs, err)
	return _c
}

func (_c *MockSDKClient_VCSDiffV1_Call) RunAndReturn(run func(request VCSDiffRequest) ([]VCSDiff, error)) *MockSDKClient_VCSDiffV1_Call {
	_c.Call.Return(run)
	return _c
}

// VCSReleasesV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) VCSReleasesV1(request VCSReleasesRequest) ([]VCSRelease, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for VCSReleasesV1")
	}

	var r0 []VCSRelease
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(VCSReleasesRequest) ([]VCSRelease, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(VCSReleasesRequest) []VCSRelease); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]VCSRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(VCSReleasesRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_VCSReleasesV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VCSReleasesV1'
type MockSDKClient_VCSReleasesV1_Call struct {
	*mock.Call
}

// VCSReleasesV1 is a helper method to define mock.On call
//   - request VCSReleasesRequest
func (_e *MockSDKClient_Expecter) VCSReleasesV1(request interface{}) *MockSDKClient_VCSReleasesV1_Call {
	return &MockSDKClient_VCSReleasesV1_Call{Call: _e.mock.On("VCSReleasesV1", request)}
}

func (_c *MockSDKClient_VCSReleasesV1_Call) Run(run func(request VCSReleasesRequest)) *MockSDKClient_VCSReleasesV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 VCSReleasesRequest
		if args[0] != nil {
			arg0 = args[0].(VCSReleasesRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSDKClient_VCSReleasesV1_Call) Return(vCSReleases []VCSRelease, err error) *MockSDKClient_VCSReleasesV1_Call {
	_c.Call.Return(vCSReleases, err)
	return _c
}

func (_c *MockSDKClient_VCSReleasesV1_Call) RunAndReturn(run func(request VCSReleasesRequest) ([]VCSRelease, error)) *MockSDKClient_VCSReleasesV1_Call {
	_c.Call.Return(run)
	return _c
}

// VCSTagsV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) VCSTagsV1() ([]VCSTag, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VCSTagsV1")
	}

	var r0 []VCSTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]VCSTag, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []VCSTag); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]VCSTag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSDKClient_VCSTagsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VCSTagsV1'
type MockSDKClient_VCSTagsV1_Call struct {
	*mock.Call
}

// VCSTagsV1 is a helper method to define mock.On call
func (_e *MockSDKClient_Expecter) VCSTagsV1() *MockSDKClient_VCSTagsV1_Call {
	return &MockSDKClient_VCSTagsV1_Call{Call: _e.mock.On("VCSTagsV1")}
}

func (_c *MockSDKClient_VCSTagsV1_Call) Run(run func()) *MockSDKClient_VCSTagsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSDKClient_VCSTagsV1_Call) Return(vCSTags []VCSTag, err error) *MockSDKClient_VCSTagsV1_Call {
	_c.Call.Return(vCSTags, err)
	return _c
}

func (_c *MockSDKClient_VCSTagsV1_Call) RunAndReturn(run func() ([]VCSTag, error)) *MockSDKClient_VCSTagsV1_Call {
	_c.Call.Return(run)
	return _c
}

// ZIPCreateV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ZIPCreateV1(inputDirectory string, outputFile string) error {
	ret := _mock.Called(inputDirectory, outputFile)

	if len(ret) == 0 {
		panic("no return value specified for ZIPCreateV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(inputDirectory, outputFile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_ZIPCreateV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZIPCreateV1'
type MockSDKClient_ZIPCreateV1_Call struct {
	*mock.Call
}

// ZIPCreateV1 is a helper method to define mock.On call
//   - inputDirectory string
//   - outputFile string
func (_e *MockSDKClient_Expecter) ZIPCreateV1(inputDirectory interface{}, outputFile interface{}) *MockSDKClient_ZIPCreateV1_Call {
	return &MockSDKClient_ZIPCreateV1_Call{Call: _e.mock.On("ZIPCreateV1", inputDirectory, outputFile)}
}

func (_c *MockSDKClient_ZIPCreateV1_Call) Run(run func(inputDirectory string, outputFile string)) *MockSDKClient_ZIPCreateV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSDKClient_ZIPCreateV1_Call) Return(err error) *MockSDKClient_ZIPCreateV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_ZIPCreateV1_Call) RunAndReturn(run func(inputDirectory string, outputFile string) error) *MockSDKClient_ZIPCreateV1_Call {
	_c.Call.Return(run)
	return _c
}

// ZIPExtractV1 provides a mock function for the type MockSDKClient
func (_mock *MockSDKClient) ZIPExtractV1(archiveFile string, outputDirectory string) error {
	ret := _mock.Called(archiveFile, outputDirectory)

	if len(ret) == 0 {
		panic("no return value specified for ZIPExtractV1")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(archiveFile, outputDirectory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSDKClient_ZIPExtractV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZIPExtractV1'
type MockSDKClient_ZIPExtractV1_Call struct {
	*mock.Call
}

// ZIPExtractV1 is a helper method to define mock.On call
//   - archiveFile string
//   - outputDirectory string
func (_e *MockSDKClient_Expecter) ZIPExtractV1(archiveFile interface{}, outputDirectory interface{}) *MockSDKClient_ZIPExtractV1_Call {
	return &MockSDKClient_ZIPExtractV1_Call{Call: _e.mock.On("ZIPExtractV1", archiveFile, outputDirectory)}
}

func (_c *MockSDKClient_ZIPExtractV1_Call) Run(run func(archiveFile string, outputDirectory string)) *MockSDKClient_ZIPExtractV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSDKClient_ZIPExtractV1_Call) Return(err error) *MockSDKClient_ZIPExtractV1_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSDKClient_ZIPExtractV1_Call) RunAndReturn(run func(archiveFile string, outputDirectory string) error) *MockSDKClient_ZIPExtractV1_Call {
	_c.Call.Return(run)
	return _c
}
