package appgitlab

import (
	"github.com/cidverse/cid/pkg/common/dependency"
	"github.com/cidverse/cid/pkg/constants"
	"github.com/cidverse/cid/pkg/core/actionsdk"
)

var mergeRequestFooter = "This PR has been generated by the [CID GitLab App](https://gitlab.com/cidverse-app)."

var gitlabNetworkAllowList = []actionsdk.ActionAccessNetwork{
	// GitHub Platform
	{Host: "github.com:443"},
	{Host: "api.github.com:443"},
	{Host: "codeload.github.com:443"},
	{Host: "uploads.github.com:443"},
	{Host: "objects.githubusercontent.com:443"},
	{Host: "raw.githubusercontent.com:443"},
	// GitHub Container Registry
	{Host: "ghcr.io:443"},
	{Host: "pkg-containers.githubusercontent.com:443"},
}

var gitlabWorkflowDependencyList = []dependency.Dependency{
	// tools
	{
		Id:             "cidverse/cid",
		Type:           "github",
		Version:        constants.Version,
		Hash:           constants.BinaryHash,
		GPGFingerprint: "76A4948E69C62589C7B0AB84E414434DF5371FB6",
	},
	// oci-containers
	{
		Id:         "podman/stable",
		Type:       "docker",
		Version:    "v5.8.1-immutable",
		Hash:       "42d8b3d789333f07e631305325a02b4ab33c3f107413e04b612973a72f1d7deb",
		Repository: "quay.io",
	},
	{
		Id:         "docker",
		Type:       "docker",
		Version:    "29.3.0-dind",
		Hash:       "1ba18449911d01f477a3fc104123c85d677addc60701b14b3fcb5381f9c4a537",
		Repository: "docker.io",
	},
	{
		Id:      "cidverse/container-images/ci-gitlab",
		Type:    "docker",
		Version: "0.1.0",
		//Hash:    "",
		Repository: "registry.gitlab.com",
	},
	{
		Id:      "cidverse/container-images/ci-gitlab-docker",
		Type:    "docker",
		Version: "0.1.0",
		//Hash:    "",
		Repository: "registry.gitlab.com",
	},
}

var gitlabWorkflowDependencies = func() map[string]dependency.Dependency {
	m := make(map[string]dependency.Dependency, len(gitlabWorkflowDependencyList))
	for _, dep := range gitlabWorkflowDependencyList {
		//slog.Debug("GitLab Dependency ID: " + dep.AsPackageUrlNoVersion())
		m[dep.AsPackageUrlNoVersion()] = dep
	}
	return m
}()
