package appgitlab

import (
	"github.com/cidverse/cid/pkg/app/appconfig"
	"github.com/cidverse/cid/pkg/core/catalog"
)

var mergeRequestFooter = "This PR has been generated by the [CID GitLab App](https://gitlab.com/cidverse-app)."

var gitlabNetworkAllowList = []catalog.ActionAccessNetwork{
	// GitHub Platform
	{Host: "github.com:443"},
	{Host: "api.github.com:443"},
	{Host: "codeload.github.com:443"},
	{Host: "uploads.github.com:443"},
	{Host: "objects.githubusercontent.com:443"},
	{Host: "raw.githubusercontent.com:443"},
	// GitHub Container Registry
	{Host: "ghcr.io:443"},
	{Host: "pkg-containers.githubusercontent.com:443"},
}

var gitlabWorkflowDependencies = map[string]appconfig.WorkflowDependency{
	"cid": {
		Id:      "cid",
		Type:    "binary",
		Version: "0.6.0",
	},
	"quay.io/podman/stable": {
		Id:      "quay.io/podman/stable",
		Type:    "oci-container",
		Version: "v5.5.2-immutable",
		Hash:    "866bbcac26adb7ff238145405fa0ade33bd7e9c7bb77a5c05f819dce8a753063",
	},
	"docker.io/docker": {
		Id:      "docker.io/docker",
		Type:    "oci-container",
		Version: "28.3.3-dind",
		Hash:    "acf2e2d09cedf21fa8f27bb0962674e33e159c744c152b248f1f7f43623ccd82",
	},
	"registry.gitlab.com/cidverse/container-images/ci-gitlab": {
		Id:      "registry.gitlab.com/cidverse/container-images/ci-gitlab",
		Type:    "oci-container",
		Version: "0.1.0",
		//Hash:    "",
	},
	"registry.gitlab.com/cidverse/container-images/ci-gitlab-docker": {
		Id:      "registry.gitlab.com/cidverse/container-images/ci-gitlab-docker",
		Type:    "oci-container",
		Version: "0.1.0",
		//Hash:    "",
	},
}
