###
# Main Configuration / Global Defaults
###

command-execution-types:
  - exec
  - container
  - nix-store

# paths
paths:
  artifact: dist

# mode
mode: exec

# project conventions
conventions:
  branching: GitFlow
  commit: ConventionalCommits
